### PR TITLE
Cleanup typings and integrate into build process

### PR DESCRIPTION
**Pull request by WoH**

### CODE REVIEW

**Comment by WoH** [comment]
This can probably be integrated in the gulp build process aswell @johartl ?
Otherwise we should update the readme to make sure `typings install` is executed

**Comment by johartl** [comment]
I wouldn't integrate it into the gulpfile if that's what you mean. Every step in the gulpfile will be executed once a file change is detected. And we probably very rarely install typings. So I think it's okay to only execute it manually.
But yes, you should definitely update the readme sections.
And one more thing: You will also need to add `typings install` to the Dockerfile.

**Comment by WoH** [comment]
Hopefully final check for you @johartl . I am a monkey comparatively in terms of the build process.
When this is done, I can finally push the new UI stuff with proper testing.

**Comment by johartl** [comment]
Actually two more things
1. In the Dockerfile the `typings install` must go before the `gulp build --release`. And since you're already making changes in that file would you mind replacing `node_modules/gulp/bin/gulp.js` with `node_modules/.bin/gulp` in the line above? This way we keep it consistent :)
2. In the readme file can you also add the `typings install` line to the section _Set up for development_ please?

**Comment by WoH** [comment]
Fixed

**Comment by johartl** [comment]
Great! You can merge it then!

**Pull request merged**
