### PR TITLE
APIService code style refactoring

### PR DESCRIPTION
**Pull request by johartl**
Turns out I don't know how to specify array types in Typescript properly :/

### CODE REVIEW

**Comment by WoH** [comment]
Should ideally be Observable<Array<Pokemon>>

**Comment by WoH** [comment]
Also, I think we should use this to do the refactoring of the ApiService, what do you think?

**Comment by WoH** [comment]
I meant `Observable<Array<Pokemon>>`, but glad you also found a bug 😆 
For some reason github wants to mess with me

**Comment by johartl** [comment]
> Also, I think we should use this to do the refactoring of the ApiService, what do you think?

Yup.

> I meant Observable>, but glad you also found a bug :laughing:

Then I'm afraid I don't know what you mean by Observable> :/

**Comment by WoH** [comment]
I edited it, for some reason, github wants to annoy me because `>` starts a quote, I apparently edited it only after you saw it. Check the comment again 😉

**Comment by johartl** [comment]
Is there any difference between `Observable<Pokemon[]>` and `Observable<Array<Pokemon>>`? Because if not I would choose the `[]`notation as it's shorter and less clunky.

**Comment by WoH** [comment]
Just syntactic sugar

**Comment by johartl** [comment]
Okay then I'm going to merge it

**Pull request merged**
