### PR TITLE
Add Yarn Lockfile

### PR DESCRIPTION
**Pull request by WoH**
No npm fanboys were harmed :laughing: 
- [Yarn](https://yarnpkg.com/en/docs/getting-started)
- [NPM to yarn](https://yarnpkg.com/en/docs/migrating-from-npm)
- We are still using npm on Travis and Docker but I'm tired of messy deps and long installations on my local machine.

### CODE REVIEW

**Comment by johartl** [comment]
7000 lines added? What is this even doing?

**Comment by WoH** [comment]
Click the blue things.

**Comment by WoH** [comment]
More blue things:
- [here](https://medium.freecodecamp.com/npm-vs-yarn-benchmark-9b456de4aa96#.yao045io9)
- [and here](https://code.facebook.com/posts/1840075619545360)

**Comment by johartl** [comment]
I read your blue things. Does this mean now that every contributor has to update the yarn lock file upon installing or removing package dependencies?

**Comment by WoH** [comment]
This should be majority vote imho. Which probably means 50/50 as it's me and you :laughing: :gun: 
If you run yarn add that should update both. If you wanna give it a try, merge it, otherwise we can leave this up until everybody and their grandma switched.

**Comment by gyachdav** [comment]
no reason to waste time on Yarn at this stage. Keep it for your next project.

**Comment by WoH** [comment]
You're right. I'll use it for myself, everyone else can run yarn for himself of enjoy the "fun" npm is.
Just don't annoy me if your deps are off.

**Comment by sacdallago** [comment]
Jezuz @WoH that was some passive-aggressive comment :D It almost wins, if it wasn't for the countless conversations between you and @MajorBreakfast

**Comment by WoH** [comment]
@sacdallago https://github.com/PokemonGoers/PokeMap-1/issues/40#issuecomment-255590416

I wasted like an hour trying to make npm update after a magic combination of npm prune, rm -rf node_modules and npm cache clean finally did the trick. I was pretty done with that wonderful dependency management at that point. Wasn't meant to sound as passive aggressive as it looks ^^ But it's not the first time we had issues (beta -> rc0) in out team, so that wasn't directed to anyone specifically but I just don't want to deal with that any more.

**Comment by gyachdav** [comment]
@woh I will do my best not to annoy you. Make sure you do the same.

**Comment by WoH** [comment]
@gyachdav I'll try to not sound like a pissed-off toddler who had his candies stolen. WIll that work? :sweat:

**Comment by MajorBreakfast** [comment]
Hehe, opinionated programming :)

**Comment by MajorBreakfast** [comment]
I heard about yarn before and I checked it out now. What I've seen are definite improvements to npm while not splitting the ecosystem because it still uses the npm registry (Due to its chaching it even eases the server load on the registry). What I'm not so sure about is whether a lock file should be in the repo. Since we're a leaf package it seems to be okay. But it's IMO a definite no-no for non-leaf packages. There `yarn.lock` should be in the `.gitignore`. Otherwise all the version resolution magic would go down the drain. `</major-breakfast-rumbling-in-an-already-closed-issue>`

**Pull request closed without merging**
