### PR TITLE
Fix: Rarity rating gets cut off

### LINKED ISSUE #110: [SCSS] Rarity rating gets cut off
The rarity rating in the POI card gets cut off when the pokemon name is too long, e.g. with Magnemite.

screenshot_20161010-232833

### PR DESCRIPTION
**Pull request by johartl**
Fixes #110

### CODE REVIEW

**Comment by MajorBreakfast** [comment]
Looks good.

**Comment by mfkaptan** [comment]
Hey @johartl I just pulled your branch `fix-pokename-size` and did a rebuild. 
This is what I get for iphone 6 (Everything looks ok)
image

And this is for iphone 5:
image

Is something wrong with my settings? Could you check this before merging?

**Review by mfkaptan — CHANGES_REQUESTED** [review]
Could you check this before merging? 
https://github.com/PokemonGoers/Catch-em-all/pull/113#issuecomment-253303339

**Comment by johartl** [comment]
The only thing I did was decreasing the font size and I thought that would cover all smaller devices. I guess we need to scale the font size depending on the available screen width. I'm going to look into it. Thanks for checking!

**Comment by sacdallago** [comment]
Sometimes these kinds of things are unavoidable. Try to fix as possible, but focus on wrapping up now.

**Comment by MajorBreakfast** [comment]
Update: In https://github.com/PokemonGoers/Catch-em-all/issues/69 we decided to use the badges `common`, `uncommon`, `rare` instead of stars for rarity. This changes things of course. I think that we should place them somewhere else. Either above or below the picture would be fine

**Comment by MajorBreakfast** [comment]
Replaced by #122

**Pull request closed without merging**
