### PR TITLE
Sidebar implemented and about page information

### PR DESCRIPTION
**Pull request by philbu**
I created a sidebar and filled the about page with some informations.

### CODE REVIEW

**Comment by WoH** [comment]
www/build should be removed. This is output of the build process.
This was the standard ionic output directory, but I thought we changed that to server/app. Weird.
However, it should be removed

**Comment by philbu** [comment]
Changed it. I was wondering were these 130000 changes came from. By the way, the output is fixed now. Not sure what caused the bug.

**Comment by WoH** [comment]
If you can squash https://github.com/PokemonGoers/Catch-em-all/pull/40/commits/32488149ae65803eb965555543c97e98b0dd91cf, https://github.com/PokemonGoers/Catch-em-all/pull/40/commits/9fa22593b63ebbe7923a8f899428e3bb0a56d056 and https://github.com/PokemonGoers/Catch-em-all/pull/40/commits/6cf6017bb6af24ba412a7328f9e95f8f493379fd, the whole thing would look a lot cleaner imo. Looks fine otherwise, I haven't checked the details though.

**Comment by johartl** [comment]
I merged develop into the sidebar branch to include the changes from #39. Otherwise your build might pass wrongly ;)

**Comment by AlexanderLill** [comment]
Oh you were merging it the same moment - I fixed one renaming error right now

**Comment by johartl** [comment]
Oops sorry then :/ 
Btw when you do `git pull --rebase` instead of `git pull` you won't have these unnecessary `Merge branch XYZ of origin into XYZ` merge commits. If you're using a git client there should be an option for that as well :)

**Comment by johartl** [comment]
What I don't like is the duplication of the header code in all pages:

``` (html)
<ion-header>
  <ion-navbar>
      <button menuToggle>
        <ion-icon name='menu'></ion-icon>
      </button>
    <ion-title>Map</ion-title>
  </ion-navbar>
</ion-header>
```

It would be nice if we could extract that to a Directive/Component:
`<navbar title="Map"></navbar>`
Since I'm already working on the #26 I will look into this. 

For now I think you can merge this. Good work :)

**Comment by johartl** [comment]
@AlexanderLill Oh actually, I noticed on thing.
Do we want to move the `app-menu.component.ts` file into a different folder? Maybe:

```
/app
  /components
    /app-menu
      app-menu.component.ts
      app-menu.component.html (renamed from app-menu.html)
  /pages
    ...
```

Sorry for the late call :(

Edit: Please see https://github.com/PokemonGoers/Catch-em-all/pull/46#issuecomment-246126263 for a final app structure guideline.

**Comment by philbu** [comment]
Okay you were quite too fast for me. Wanted to resolve the merge conflict and folder location right now. Thanks @johartl

**Comment by johartl** [comment]
I did two more things
- I extract everything navbar related into a designated component `nav-sidemenu`. This way we can keep the `app.ts` a bit cleaner
- The sidebar was showing a vertical scroll bar which I removed. 

@philbu Now you can have a look at the changes I've made and review them ;) 
If everything is fine you are good to merge :+1:

**Comment by philbu** [comment]
Everything is fine so I will finally merge it. 
Nice css fix for that annoying scrollbar in our sidebar btw :+1:

**Pull request merged**
