### PR TITLE
Stop displaying the Pokemon Ids

### PR DESCRIPTION
**Pull request by MajorBreakfast**
Stop displaying the Pokemon ids as requested by @gyachdav in #69

### CODE REVIEW

**Comment by MajorBreakfast** [comment]
id2
id1

**Review by mfkaptan — APPROVED** [review]

**Review by mfkaptan — COMMENTED** [review]
Should we also remove the id from poke-poi-card (or do we call it bottom sheet)?

**Review by WoH — APPROVED** [review]

**Comment by MajorBreakfast** [comment]
Adding the commit for removing the id on the card now...

**Comment by MajorBreakfast** [comment]
id1
id2

**Comment by MajorBreakfast** [comment]
@WoH @mfkaptan (Still) approved?

**Review by WoH — APPROVED** [review]

**Pull request merged**
