### PR TITLE
Add poke-rarity-badge component

### PR DESCRIPTION
**Pull request by AlexanderLill**
Hi,

I added the pokemon rarity as a star-badge (1 to 3 stars) to the PokeDex page.

Take a look how you like it, I had to test with hardcoded values because the @PokemonGoers/pokedata API is currently offline.

I used the same algorithm as for the rarity texts, e.g. less than 1 in 1000 Pokemon: 3 stars, x in 1000 Pokemon: 2 stars, more than 1 in hundred: 1 star.

PS: I reverted my accidental push to develop with this commit: 146c00a7dbed0e3af92218f5e66455dada474235

... don't ask ;)

### CODE REVIEW

**Comment by AlexanderLill** [comment]
screenshot from 2016-10-08 18-12-21
screenshot from 2016-10-08 18-12-51

Looks like this - feel free to change the design or comment, otherwise I will merge it later today / tomorrow

**Review by AlexanderLill — COMMENTED** [review]
Oh, now I see what you meant with "this is overly complicated" ;)

It made it easier to change the algorithm for the number of stars, though. Maybe :)

**Comment by WoH** [comment]
Not for 3 stars though.
Even if you do 5.
Everything beyond seems unrealistic.

Edit: If the logic is more difficult you could go for an array with 1's and 0's which is the most flexible solution. However maintaining nested if/else statements is a nightmare, so you'd end up refactoring the method.

**Comment by AlexanderLill** [comment]
@WoH check one last time if this is also okay, or if you like the stars more in your order :)

**Comment by WoH** [comment]
The new order is super confusing :/

Edit: Please move completely unrelated Code style changes out of the feature PR's.

**Comment by AlexanderLill** [comment]
Are you serious? :O

But it looks so much better :P ... Okay...
If you want to wait for another opinion, let's wait.
If you are super-serious, revert my last commit and let's merge :)

Edit: So it would be better to create a new PR only for Code Style Changes? I see :) I started with a handful of changes, and then they got more and more ... ;) Next time?

**Comment by WoH** [comment]
Let's say a discussion beaks out on either one of the concerns (feature, code style or whatever in another component). One will always interrupt the merge of the other and it won't be clear which pr is supposed to fix what. Also imagine the PR for feature 1 also improves feature 2 but breaks things there. Other ppl will be clueless as to why it happened or at least it will make things harder to retrace.

I don't know, maybe there is only space for one order of stars to process in my brain. Tag the others for a democratic vote or 1v1 tomorrow in Garching?

Edit: In all seriousness, this is minor, so ready to merge imho.

**Review by WoH — APPROVED** [review]

**Comment by AlexanderLill** [comment]
Yes, let's ask the others which order they prefer - filled stars in the
right, or "normal" order of stars, filling from left to right :)
@PokemonGoers/Catch-em-all

I added the stars to the POI-card too. What is the longest pokemon name?
Might get too much in one line in that case, dunno if it wraps or just gets
cut-off :|

**Pull request merged**
