### PR TITLE
Update tile layer

### PR DESCRIPTION
**Pull request by johartl**
This changes the tile layer according to https://github.com/PokemonGoers/general/issues/1.

### CODE REVIEW

**Review by AlexanderLill — APPROVED** [review]

**Comment by AlexanderLill** [comment]
Works for me ;)

**Review by WoH — APPROVED** [review]

**Comment by sacdallago** [comment]
This is weird... I still see OCM, maybe the setting is not correctly passed to the map on init in the package? @PokemonGoers/pokemap-1

**Comment by johartl** [comment]
Can you check if clearing your browser cache works?

**Comment by sacdallago** [comment]
Good. I'll use incognito to debug from now on: noted.

**Comment by johartl** [comment]
It's strange though as every build comes with a unique hash that is appended to all bundled files. That should definitely bypass your cache :/

**Comment by sacdallago** [comment]
My chrome settings are some of the most fucked up settings you'll ever encounter.

Anyway: I still have not been added to the hockeyapp :) and I wrote my email to... I don't remember who. Can someone look into this?

**Comment by johartl** [comment]
I've invited you but your status still reads 'pending'. I resend you the invitation. Let me know if that helped.

**Comment by sacdallago** [comment]
still nothing :cry:

**Comment by johartl** [comment]
Maybe check your spam folder?

**Comment by sacdallago** [comment]
Did that, and every other spam folder there is :D I fear you have the wrong address? Send me an email, like, just an ordinary mail from you to me ❤️

**Pull request merged**
