### PR TITLE
Build environment support / enableProdMode()

### PR DESCRIPTION
**Pull request by johartl**
This PR adds a global variable `ENV` which is either `dev` or `prod` depending on the environment the app is running in. 
With this we are able to call `enableProdMode()` when running inside the docker container which will disable some checks in Angular internally and speed up the app.
More information here https://angular.io/docs/ts/latest/api/core/index/enableProdMode-function.html

### CODE REVIEW

**Comment by WoH** [comment]
Should be fine, do you want me to test it or does my "looks good" already make you comfortable?

**Comment by WoH** [comment]
I'll label this as a bugfix, since it should take care of some errors in the demo.

**Comment by johartl** [comment]
It's okay I tested it and the changes are not too large :)
After I merged to develop you won't see the following log message in the chrome developer console anymore when opening the live demo (http://catch-em-all-0a600d65.c65978f4.svc.dockerapp.io:4898/).

`Angular 2 is running in the development mode. Call enableProdMode() to enable the production mode.`

That's how you know it worked. Unfortunately we don't have builds for feature branches.

**Comment by WoH** [comment]
Exactly what I meant

**Pull request merged**
