### PR TITLE
Pokedex details redesign

### PR DESCRIPTION
**Pull request by MajorBreakfast**
Note: This also includes the minor change of #116 (postinstall hook)

Implements the design change of #121 

This PR is mainly about the broad layout change and improvements in clarity (#120 cryptic glyphs). Minor layout tweaks and tweaks to shapes and colors are not included. We can handle iterative improvements in additional PRs. I'd like to get this merged soon, please don't get hung up on appearance details. I will take your design feedback into account, just not in this PR! :)

pokedex-redesign

### CODE REVIEW

**Comment by MajorBreakfast** [comment]
comparison

**Comment by MajorBreakfast** [comment]
subtle-colors

Okay, now we're back to subtle colors again. PLZ review my code.

**Comment by MajorBreakfast** [comment]
I've added a commit that takes care of #119 (Removal of creative commons license statement)

**Comment by WoH** [comment]
Good: 
- Design
- Code looks fine

Not so good:
- 2 Different topics in one PR

The stats could be contained within a card maybe? I like cards...

**Comment by MajorBreakfast** [comment]
> 2 Different topics in one PR

Jep, I'd fix it, but I don't think it's worth the effort

**Comment by WoH** [comment]
No, just try to avoid it in the future

**Comment by sacdallago** [comment]
I still don't like the clouds 🙈 If you get rid of that and use some rectangles, in my view, it looks sexy ( @WoH ).

About two issues in one PR, I agree with both points: better not do this next time, but too much to do now to close this and open two separate ones **IF** this PR is ok for both problems

**Comment by MajorBreakfast** [comment]
@WoH Will do.

@sacdallago I'll take a look at getting rid of the clouds later. It's a bit tricky. Simply removing the radii doesn't work. It looked bad when I tried it. Maybe I get an idea later.

@philbu Thx for telling me that the current Pokemon image in the evolutions chart wasn't square. The problem was cause by the colored border.

I'm merging this now. Thanks for all the feedback.

**Pull request merged**
