### PR TITLE
Ionic2

### PR DESCRIPTION
**Pull request by WoH**

### CODE REVIEW

**Comment by johartl** [comment]
This PR also contains a lot of changes with respect to deployment. So please have a look at the Dockerfile and travis.yml as well :)

**Comment by WoH** [comment]
Final vote @MajorBreakfast, looks good to me, but it's a lot of my stuff.

**Comment by sacdallago** [comment]
Jezuz this PR is huge :D but I understand why

**Comment by johartl** [comment]
I've looked at the code for quite some time and changed/added a lot myself. So I'm also waiting for @MajorBreakfast. Or maybe someone else? :)

**Comment by MajorBreakfast** [comment]
@johartl, @WoH  Sry I didn't see it in time... no matter we can always change stuff

**Pull request merged**
