### PR TITLE
Own popover

### PR DESCRIPTION
**Pull request by MajorBreakfast**
Don't merge yet. It's in the works.
- [x] CSS Styling for own popover, responsive design
- [ ] Fix user interaction with toggles and sliders
- [ ] Fix tab switching
- [ ] Implement click to open and closing mechanism

### CODE REVIEW

**Comment by AlexanderLill** [comment]
Did you also fix the wrapping of longer content? E.g. my full list of pokemon is longer than the popover without a scroll bar, does that work? :)

**Comment by MajorBreakfast** [comment]
@AlexanderLill Once your Pokemon list is in develop I'm going to merge/rebase.

**Comment by WoH** [comment]
Can we maybe close this until it's ready for review?

**Comment by AlexanderLill** [comment]
I would agree with WoH here ... dont see a point in having this open all the time, if it is not really an active pull request... @MajorBreakfast

**Comment by sacdallago** [comment]
Yup, this doesn't make sense. I close it and you can open when ready, move the bullet points in an issue if necessary

**Pull request closed without merging**
